#!/bin/bash

# List of Git repositories
repositories=(
    "https://github.com/carlospolop/PEASS-ng"
    "https://github.com/PowerShellMafia/PowerSploit"
    "https://github.com/unode/firefox_decrypt"
    # Add more repositories as needed
)
local_path="/opt/exploits/"

# Function to update a Git repository
update_repository() {
    local repo_path="$local_path/$(basename "$1")"
    
    # Check if the directory exists and is not empty
    if [ -d "$repo_path" ] && [ -n "$(ls -A "$repo_path")" ]; then
        # Directory exists and is not empty
        echo "Directory '$repo_path' already exists and is not empty. Performing forced update."

        # Fetch changes from the remote repository and reset to the remote branch
        git -C "$repo_path" pull

        # Print a separator for better output
        echo "------------------------"
    else
         # Clone the repository into the specified directory
         git clone "$1" "$repo_path"
    fi
}

# Iterate through repositories and update each one
for repo in "${repositories[@]}"; do
    update_repository "$repo"
done
