#!/bin/bash

# List of Git repositories
repositories=(
    "https://github.com/carlospolop/PEASS-ng"
    "https://github.com/PowerShellMafia/PowerSploit"
    "https://github.com/unode/firefox_decrypt"
    # Add more repositories as needed
)
local_path="/opt/exploits/"

# Function to update a Git repository
update_repository() {
    local repo_path="$local_path/$(basename "$1")"
    
    # Check if the directory exists
    if [ -d "$repo_path" ]; then
        # Change to the repository directory
        cd "$repo_path" || exit
        
        # Perform git pull to update the repository
        git pull
        
        # Print a separator for better output
        echo "------------------------"
    else
         # Create the repository directory
         mkdir "$repo_path"
         cd "$repo_path" || exit
         git clone "$1"
    fi
}

# Iterate through repositories and update each one
for repo in "${repositories[@]}"; do
    update_repository "$repo"
done
